repos:
  - repo: https://github.com/bavadeve/org-security-workflows
    rev: 4d1922889a73693bb13a46502535d2864529eb98 # or use a specific tag or commit hash
    hooks:
      - id: check-forbidden-filetypes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ["--maxkb=100"]
      - id: check-merge-conflict
