name: Org Security Scan

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  security-scan:
    uses: bavadeve/org-security-workflows/.github/workflows/check-forbidden-filetypes.yml@main